<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.3 on win32)" generated="2024-05-31T22:19:56.460919" rpa="false" schemaversion="5">
<suite id="s1" name="Search Flight" source="c:\Users\acer\Mobile-Automation-RobotFramework\Suites\Search_Flight.robot">
<test id="s1-t1" name="User Search Flight Invalid Flight Number" line="26">
<kw name="Open Flight Application" owner="base" type="SETUP">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:01.085657" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D7410&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:05.160177" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D7CB0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:09.231624" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8C50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:13.298043" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-05-31T22:20:13.298043" elapsed="0.015624">No application is open</status>
</kw>
<msg time="2024-05-31T22:20:13.329291" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:13.329291" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8F20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>${REMOTE_URL}</arg>
<arg>platformName=${platformName}</arg>
<arg>udid=${UDID}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-05-31T22:19:56.930573" elapsed="16.398718">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8F20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<status status="FAIL" start="2024-05-31T22:19:56.930573" elapsed="16.398718">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8F20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Close Flight Application" owner="base" type="TEARDOWN">
<kw name="Close Application" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:13.329291" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-05-31T22:20:13.329291" elapsed="0.020645">No application is open</status>
</kw>
<msg time="2024-05-31T22:20:13.351452" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:13.351452" level="FAIL">No application is open</msg>
<doc>Closes the current application and also close webdriver session.</doc>
<status status="FAIL" start="2024-05-31T22:20:13.329291" elapsed="0.022161">No application is open</status>
</kw>
<status status="FAIL" start="2024-05-31T22:20:13.329291" elapsed="0.022161">No application is open</status>
</kw>
<status status="FAIL" start="2024-05-31T22:19:56.930573" elapsed="16.420879">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8F20&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Also teardown failed:
No application is open</status>
</test>
<test id="s1-t2" name="User Search Flight Invalid Flight Number" line="32">
<kw name="Open Flight Application" owner="base" type="SETUP">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:17.431614" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D71A0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:21.491327" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D61E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:25.563669" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D6360&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:29.592865" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-05-31T22:20:29.592865" elapsed="0.008960">No application is open</status>
</kw>
<msg time="2024-05-31T22:20:29.605820" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:29.607820" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4FB680&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>${REMOTE_URL}</arg>
<arg>platformName=${platformName}</arg>
<arg>udid=${UDID}</arg>
<arg>appPackage=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-05-31T22:20:13.361456" elapsed="16.255359">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4FB680&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<status status="FAIL" start="2024-05-31T22:20:13.361456" elapsed="16.255359">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4FB680&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Close Flight Application" owner="base" type="TEARDOWN">
<kw name="Close Application" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-05-31T22:20:29.620811" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-05-31T22:20:29.619813" elapsed="0.002998">No application is open</status>
</kw>
<msg time="2024-05-31T22:20:29.626808" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:29.628808" level="FAIL">No application is open</msg>
<doc>Closes the current application and also close webdriver session.</doc>
<status status="FAIL" start="2024-05-31T22:20:29.619813" elapsed="0.010994">No application is open</status>
</kw>
<status status="FAIL" start="2024-05-31T22:20:29.618814" elapsed="0.013055">No application is open</status>
</kw>
<status status="FAIL" start="2024-05-31T22:20:13.361456" elapsed="16.271411">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4FB680&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Also teardown failed:
No application is open</status>
</test>
<status status="FAIL" start="2024-05-31T22:19:56.478909" elapsed="33.157956"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Search Flight">Search Flight</stat>
</suite>
</statistics>
<errors>
<msg time="2024-05-31T22:20:01.085657" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D7410&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:05.160177" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D7CB0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:09.231624" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4F8C50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:13.329291" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:13.351452" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:13.361456" level="WARN">Multiple tests with name 'User Search Flight Invalid Flight Number' executed in suite 'Search Flight'.</msg>
<msg time="2024-05-31T22:20:17.431614" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D71A0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:21.491327" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D61E0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:25.563669" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001BBAA4D6360&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-31T22:20:29.605820" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-31T22:20:29.626808" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
